name: college_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  dotted_border: ^2.1.0
  file_picker: ^8.0.0+1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_emoji_feedback: ^0.1.2
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.0
  image_picker: ^1.0.8
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.3
  rename_app: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
