  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXp3tImTubOUZWSWwPQXdOoHY3nLzko50',
    appId: '1:308148557894:web:361233044082e0a42ed247',
    messagingSenderId: '308148557894',
    projectId: 'graduationproject-fd501',
    authDomain: 'graduationproject-fd501.firebaseapp.com',
    databaseURL: 'https://graduationproject-fd501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduationproject-fd501.appspot.com',
    measurementId: 'G-5H66XJ8KD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHYeLfHHn4BS8pZT2axKLqvINVpV39GVU',
    appId: '1:308148557894:android:20b98cf8f44ef47c2ed247',
    messagingSenderId: '308148557894',
    projectId: 'graduationproject-fd501',
    databaseURL: 'https://graduationproject-fd501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduationproject-fd501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImJptudtZcS9YKxbyqUXn5T8HBjU99Og',
    appId: '1:308148557894:ios:623fb0e8e76641182ed247',
    messagingSenderId: '308148557894',
    projectId: 'graduationproject-fd501',
    databaseURL: 'https://graduationproject-fd501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduationproject-fd501.appspot.com',
    iosBundleId: 'com.example.collegeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDImJptudtZcS9YKxbyqUXn5T8HBjU99Og',
    appId: '1:308148557894:ios:623fb0e8e76641182ed247',
    messagingSenderId: '308148557894',
    projectId: 'graduationproject-fd501',
    databaseURL: 'https://graduationproject-fd501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduationproject-fd501.appspot.com',
    iosBundleId: 'com.example.collegeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXp3tImTubOUZWSWwPQXdOoHY3nLzko50',
    appId: '1:308148557894:web:c50ddf227e8248712ed247',
    messagingSenderId: '308148557894',
    projectId: 'graduationproject-fd501',
    authDomain: 'graduationproject-fd501.firebaseapp.com',
    databaseURL: 'https://graduationproject-fd501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduationproject-fd501.appspot.com',
    measurementId: 'G-WWRYKGY1ZR',
  );

}